### ISSUE TITLE
Add github workflow to auto-build pdf

### ISSUE THREAD

**Issue by lento234** [lento234/cv#2]
Based on awesome-cv workflow perhaps:

```
name: Compile PDFs

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Compile
      run: make

    - uses: actions/upload-artifact@v2
      with:
        name: examples
        path: examples/*.pdf
```
